source 'https://rubygems.org'
gem 'onlyoffice_documentserver_conversion_helper', git: 'https://github.com/onlyoffice-testing-robot/onlyoffice_documentserver_conversion_helper.git'
gem 'onlyoffice_logger_helper', git: 'https://github.com/onlyoffice-testing-robot/onlyoffice_logger_helper.git'
gem 'onlyoffice_s3_wrapper'
gem 'onlyoffice_testrail_wrapper', git: 'https://github.com/onlyoffice-testing-robot/onlyoffice_testrail_wrapper'
gem 'palladium', git: 'https://github.com/flaminestone/palladium.git'
gem 'rspec'
gem 'rubocop'
